### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by johnnyman727** [tessel/project#106]
I did some thinking about how we might want to focus our collective energy over the next few weeks to nail out all the highest priority targets. We can respectfully ignore any issues/PRs that don't fall into the milestone targets below except for egregious issues that have a specific label (like 'urgent') and outstanding PRs.

Here are the suggested milestones - feedback is welcome:

### Complete by 10/26/15

Kelsey and Jon will be at Fullstack conference in London running people through the first run experience. Let's knock out any lingering problems that makes it difficult to get started with Tessel 2.

- [x] [Node 4.x CLI compatibility](https://github.com/tessel/t2-cli/issues/321)
- [x] [Node 4.2.1 running on Tessel 2](https://github.com/tessel/openwrt-tessel/issues/27)
- [x] [Fix USB Booting issues](https://github.com/tessel/t2-cli/pull/386)

### Complete by 11/4/15

This exists, but I'm not sure what the items were

### Complete by 11/24/15
- [x] [Make Ambient/IR modules compatible with T2](https://github.com/tessel/t2-firmware/issues/112) @johnnyman727 (ostensibly functional, just waiting for testing on Tessel 1)
- [x] [RFID compatibility with T2](https://github.com/tessel/t2-firmware/issues/111) @johnnyman727 (ostensibly functional, just waiting for testing on Tessel 1)
- [x] [GPS compatibility with T2](https://github.com/tessel/gps-a2235h/issues/19) @johnnyman727 (ostensibly functional, just waiting for testing on Tessel 1)
- [x] [Add the ability to enable and disable wifi](https://github.com/tessel/t2-cli/issues/394) @johnnyman727
- [x] [Add the ability to make Tessel an access point](https://github.com/tessel/t2-cli/issues/87) @HipsterBrown 
- [x] [Add the ability to get a root shell](https://github.com/tessel/t2-cli/issues/87) @Student007 

### Complete by 12/09/15
- [x] [Report wifi connection success](https://github.com/tessel/t2-cli/issues/395) @frijol
- [x] [Make it so you can connect to wifi networks with no password](https://github.com/tessel/t2-cli/issues/373) @HipsterBrown
- [x] [Add the option to select network security type](https://github.com/tessel/t2-cli/issues/393) @HipsterBrown 
- [x] Fix [t2-compiler](https://github.com/tessel/t2-compiler) @tcr 

### Complete by 01/06/16
- [x] [Fix USB dropping off the bus occasionally](https://github.com/tessel/t2-firmware/issues/102) @johnnyman727 (released off-schedule as firmware build 0.0.7)
- [x] [CLI identifies binary deps and can inject them](https://github.com/tessel/t2-cli/issues/96) @rwaldron 
- [x] [Get a server up and running that can serve binary dependencies](https://github.com/tessel/t2-compiler/issues/12) @reconbot 

Several serious issues:
- [x] [You can only `push` a bundle once successfully](https://github.com/tessel/t2-cli/issues/415)
- [x] [First use of `t2 ap` over USB will crash](https://github.com/tessel/t2-cli/issues/475) @hipsterbrown
- [x] [t2 wifi -l only works once per boot](https://github.com/tessel/t2-cli/issues/350)
- [x] [control+c doesn't end Node processes (over LAN?)](https://github.com/tessel/t2-cli/issues/419)

### Complete by 02/03/16 (moved from 01/20/2016)
- [x] [Commands sometimes hang on "Looking for your Tessel..."](https://github.com/tessel/t2-cli/issues/271)
- [x] Make USB BLE module work with T2 CLI 
- [x] Make FRE for USB BLE @Frijol 
- [x] Make Flash Drives mount automatically
- [x] Make FRE for Flash Drive @Frijol 
- [x] [pin.pull in firmware](https://github.com/tessel/t2-firmware/issues/145) @johnnyman727
- [x] [Add Tessel networking utilities to the `tessel` module](https://github.com/tessel/t2-firmware/issues/129) @HipsterBrown

### Complete by 03/17/16
- [ ] [Make USB camera/audio module functioning with T2 CLI and OpenWRT]
(https://github.com/tessel/hardware-modules/issues/12) @rwaldron 
- [x] Make USB 3G module work out of the box @HipsterBrown 
- [ ] [PWM Out in firmware](https://github.com/tessel/t2-firmware/issues/21)
- [x] [pulseIn in firmware](https://github.com/tessel/t2-firmware/issues/22)
- [ ] Get firmware updates over USB working

### Complete by 04/17/2016
- [x] [Add the ability to print out latest Tessel logs](https://github.com/tessel/t2-cli/issues/88) (Moved from "Spec Completion")
- [ ] [Rust Blinky works](https://github.com/tessel/t2-cli/pull/292) @flaki 
- [ ] [Python Blinky works](https://github.com/tessel/t2-cli/issues/201)

**Comment by Frijol** [comment]
Re using Github milestones for this https://github.com/ZenHubIO/support/issues/44
Anyone have experience with Zenhub? It's native to Github and free for open source

**Comment by johnnyman727** [comment]
I use Zenhub but didn't know that they have multiple repo Milestone support - that's great. I'll try it ou.

**Comment by rwaldron** [comment]
I just updated the list items to be checkbox items

**Comment by Student007** [comment]
@johnnyman727 I would suggest to make a milestone or a task list (and part of one of the milestones) about **usability improvements** to collect all that things and **give it a home** (and a **badge**).

But don't forgot/blend out a lot of that things could get deep impact but would be reasonable also for facing usage faults and behaviors early. So they are not to be started after the last milestone is finished. 

It is about starting yesterday but to be landed tomorrow. 

- https://github.com/tessel/t2-cli/issues/396
- https://github.com/tessel/t2-cli/pull/381
- https://github.com/tessel/t2-cli/issues/356
- https://github.com/tessel/t2-cli/issues/340
- https://github.com/tessel/t2-cli/issues/287
- https://github.com/tessel/t2-cli/issues/257
- https://github.com/tessel/t2-cli/issues/253
- https://github.com/tessel/t2-cli/issues/212
- https://github.com/tessel/t2-cli/issues/147

(result by short cross looking issues)

**Comment by Frijol** [comment]
@johnnyman727 I like the idea & the simplicity of these milestones, but it looks like most of them are already in progress by you or others. Would like to be able to use this or possibly Zenhub so that I/others can decide what to work on next. Can we create an organized Zenhub backlog to fulfill this need?

**Comment by johnnyman727** [comment]
@Frijol yes, that's a valid point. I think it's actually a good thing that people are already working on these features because they will be more likely to get done. For new contributors. Perhaps we can encourage bug fixes (see note at the top about "urgent" bugs). What do you think about that?

**Comment by Frijol** [comment]
that sounds good. Also I've just poked through the Zenhub boards and sorted them out; separating "Backlog" from "To do" is useful.

**Comment by reconbot** [comment]
@johnnyman727 I’m all over "Get a server up and running that can serve binary dependencies” do we have a repo for that server or an issue I can track?

**Comment by rwaldron** [comment]
@reconbot here's the latest compiler script: https://github.com/tessel/t2-compiler/tree/tcr-new

**Comment by rwaldron** [comment]
![](https://dl.dropboxusercontent.com/u/3531958/tessel2/bin-module-server-notes-1.jpg)
![](https://dl.dropboxusercontent.com/u/3531958/tessel2/bin-module-server-notes-2.jpg)

**Comment by Frijol** [comment]
@johnnyman727 do we have issue links for these two items from above?

 Get a server up and running that can serve binary dependencies @reconbot
 Make USB video/audio module functioning with T2 CLI and OpenWRT @tcr

**Comment by Frijol** [comment]
if not I can make them

**Comment by johnnyman727** [comment]
I don't believe we do. That'd be great if you could make them.

**Comment by Frijol** [comment]
done (linked above)

**Comment by Frijol** [comment]
...we shipped, so I'm going to resolve this
