### ISSUE TITLE
Tasks for Tessel Camp

### ISSUE THREAD

**Issue by johnnyman727** [tessel/project#199]
- [x] Node 6 CLI compatibility (fixing `usb` and moving it to the `tessel` repo): https://github.com/tessel/t2-cli/issues/842
- [x] Add ADC interrupts in an effort to land the `stability` branch of firmware https://github.com/tessel/t2-firmware/pull/204
- [x] Rust API support https://github.com/tessel/tessel-rust/issues
- [ ] Mesh networking support
- [x] Fixing the documentation <s>https://github.com/tessel/t2-docs/issues/55</s>, <s>https://github.com/tessel/t2-docs/issues/91</s>
- [ ] Database support and tutorial
- [ ] Fix attiny modules https://github.com/tessel/ambient-attx4/issues/69
- [ ] Build more hardware modules in Kicad!
- [ ] tessel.io redesign https://github.com/tessel/tessel.io/issues/102
- [ ] discussion of current storage (https://github.com/tessel/t2-docs/issues/94) and what we want it to look like if upgraded
- [x] Fix major `t2-compiler` [bugs like this one](https://github.com/tessel/t2-compiler/issues/17)
- [ ] Bridged mode https://github.com/tessel/t2-cli/issues/759
- [ ] Either make tessel.io/opensource up to date per https://github.com/tessel/tessel.io/issues/7 or design a better way to do this
- [x] Fix RFID module issue https://github.com/tessel/rfid-pn532/issues/30
- [x] Form working groups

**Comment by kevinmehall** [comment]
> fixing usb and moving it to the tessel repo

Should I transfer it to the tessel org now?

**Comment by tcr** [comment]
@kevinmehall That would be great!

**Comment by tcr** [comment]
I'll be working on the Rust API this weekend. Goals:

* Get the Accelerometer sensor working, written, and uploaded to crates.io.
* Merge I2C support (preliminary) into master.
* Make decision on event loop vs. synchronous code.
* Clean up README.

I'll then move on to helping Node 6 LTS be supported by t2-cli.

**Comment by kevinmehall** [comment]
[Transferred](https://github.com/tessel/node-usb)

**Comment by johnnyman727** [comment]
I'll be working on:
* Making firmware ADC calls using interrupts and merge the `stability` branch
* Looking over @tcr's shoulder at the Rust API
* Fix `attiny`-based modules

**Comment by Frijol** [comment]
I'm working on docs/repo consolidation

**Comment by Frijol** [comment]
Anything we need to discuss as group from https://github.com/tessel/project/issues/24 @tcr?

**Comment by Frijol** [comment]
Closing as some of these issues are out of date and others are in their own issues
