### ISSUE TITLE
Open Sourcing Checklist

### ISSUE THREAD

**Issue by tcr** [tessel/project#35]
Publicizing the existence of the Tessel Project as an organization.

Tasks

* [x] Forum post for announcing this (rehashed email post probably)
* [x] Should we clean any history from the tessel-project repo? We mentioned doing that for some sensitive items
* [x] Should we remove mentionds of nominees for candidacy on tessel-project

Open questions

* [x] Can we disclose our membership in the dojo foundation. is there some public resource we can point to

Content of outgoing email

* [x] Open source group / page
* [x] Push for Slack signup

Non-essential

* [ ] Update tessel.io with banner and more https://github.com/technicalmachine/technical-io/issues/325
* [ ] Is team@technical.io support@technical.io all our continued endpoints for resolving orders?
* [ ] Open source tessel.io website (and trim its git history)
* [ ] do we move all the technical machine social media over to "tessel"? i.e. @tesselproject

**Comment by Frijol** [comment]
Is this resolved @tcr ?

**Comment by tcr** [comment]
This item is split into #48, #49, and #45.
