### ISSUE TITLE
T2 completeness tracking

### ISSUE THREAD

**Issue by Frijol** [tessel/project#70]
This issue is for tracking T2 features which must be completed before ship. Discuss below what should/shouldn't be on this list.

## Hardware

* [x] Final hardware design
* [x] Pilot batch of 100
* [x] [FCC cert](https://github.com/tessel/project/issues/79)
* [x] CE cert
* [ ] Full manufacturing

## Firmware
* [x] I2C
* [x] SPI
* [x] UART
* [x] LEDs
* [x] Digital read/write
* [x] Interrupts
* [x] Analog read/write
* [ ] [Neopixels](https://github.com/tessel/t2-firmware/issues/24)
* [ ] [Reading pulses](https://github.com/tessel/t2-firmware/issues/22)

## OpenWRT
* [x] BLE drivers
* [x] audio/video drivers
* [x] flash drive mounting drivers
* [ ] 3g/4g dongle integration

## CLI
[Milestone tracking here](https://github.com/tessel/t2-cli/milestones)

* [x] [Continuous Tesselation](https://github.com/tessel/t2-cli/milestones/Continuous%20Tesselation)
* [x] [Easy Updation](https://github.com/tessel/t2-cli/milestones/Easy%20Updation)
* [x] [Complete Speculation](https://github.com/tessel/t2-cli/milestones/Complete%20Speculation)
* [ ] [Bonus Pointation](https://github.com/tessel/t2-cli/milestones/Bonus%20Pointation)
* [ ] [Complete Speculation](https://github.com/tessel/t2-cli/milestones/Finally%20Publication)

I'm not including `t2 status`, `t2 ap`, or `t2 root` command because, although they are super awesome features, they aren't absolutely critical to shipping. 

## Docs
- [x] [Milestone tracking](https://github.com/tessel/t2-docs/milestones)

## Start
[Milestone tracking](https://github.com/tessel/t2-start/milestones)

* [ ] [USB modules added](https://github.com/tessel/t2-start/issues/18)
* [x] [Irrelevant tenpin modules removed](https://github.com/tessel/t2-start/issues/17)
* [ ] [Image assets all T2](https://github.com/tessel/t2-start/issues/16)
* [ ] General checkover for correctness
* [ ] [Start experience up at tessel.io/start](https://github.com/tessel/t2-start/issues/26)

## Modules working/documented

* [ ] [USB modules](https://github.com/tessel/hardware-modules/issues/6)
* [ ] [ten-pin modules](https://github.com/tessel/hardware-modules/issues/7)
* [ ] [Community modules](https://github.com/tessel/hardware-modules/issues/5)
* [ ] DIY: any documentation updates needed?

## Language Support
- [x] JS
- [ ] [Python](https://github.com/tessel/tessel-python)
- [ ] [Rust](https://github.com/tessel/rust-tessel)

## Platform support
* [x] OSX
* [x] Linux
* [ ] Windows (possibly just https://github.com/tessel/t2-cli/issues/64)

**Comment by flaki** [comment]
How about platform support? I noticed the other day that `t2-cli` doesn't work on Windows (at least, for me). Are we aiming for Windows platform support for the t2, and if yes, what is the timing? (launch? later?). If the answer is yes, it should be tracked above, too, I think.

**Comment by Frijol** [comment]
Ah, good point. @johnnyman727 do you know the status of t2-cli on Windows? I haven't tried it but know that `t2 provision` has unix reliance with current implementation

**Comment by johnnyman727** [comment]
@Frijol you have it exactly right.

**Comment by Frijol** [comment]
Timeline update:
We think we have a software fix in for the FCC certification issue that has been blocking us, as well as a hardware fix for a CE certification. The fixes are currently in testing, and we should hear back any day.
Since the CE issue fix is hardware, Tessel 2 requires another board revision. These revised boards will then be sent in again for FCC and CE certification. This takes 2-3 weeks.
It will then take another 6 weeks or so to ramp up into full manufacturing and get them shipped.

**Comment by Frijol** [comment]
Deprecated, https://github.com/tessel/project/issues/106 is more useful for this
